INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (2,'Chrysanthemum.jpg','Chrysanthemum.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (3,'Desert.jpg','Desert.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (4,'Hydrangeas.jpg','Hydrangeas.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (4,'Jellyfish.jpg','Jellyfish.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (6,'Koala.jpg','Koala.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (7,'Lighthouse.jpg','Lighthouse.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (8,'Penguins.jpg','Penguins.jpg');
INSERT INTO `restu`(`id`, `food`, `photo`) VALUES (9,'Tulips.jpg','Tulips.jpg');

